Table Cliente {
  id_cliente serial [pk, not null]
  nombre varchar(100) [not null]
  telefono numeric(15,0) [not null] 
  direccion varchar(200) [not null]
  email varchar(100) [not null]
}

Table Pedido {
  id_pedido serial [pk, not null]
  id_cliente int [not null, ref: > Cliente.id_cliente]
  fecha_hora timestamp [not null]
  total numeric(10,2) [not null]
  estado varchar(20) [not null] 
}

Table Producto {
  id_ingrediente serial [pk, not null, ref: > Inventario.id_ingrediente]
  id_producto serial [pk, not null]
  nombre varchar(100) [not null]
  descripcion text
  precio numeric(8,2) [not null]
}

Table Detalles_Reparto {
  id_producto int [not null, ref: > Producto.id_producto]
  hora_salida timestamp
  hora_entrega_estimada timestamp

}

Table Inventario {
  id_pedido serial [pk, not null, ref: >Pedido.id_pedido]
  id_ingrediente serial [pk, not null]
  nombre varchar(100) [not null]
  cantidad_disponible numeric(10,2) [not null]
  unidad_medida varchar(20) [not null]
}


Table Detalles_Entrega {
  id_producto int [not null, ref: > Detalles_Reparto.id_producto]
  hora_entrega timestamp
  persona_quien_recibe varchar(100)
  firma_cliente varchar(100)
  id_Detalles_Entrega serial [pk, not null]
}